name: UltiTools-Menu
version: '${project.version}'
main: com.ultikits.plugins.menu.PluginMain
base-package: com.ultikits.plugins.menu
api-version: 630
identify-string: ultimenu
authors: [ wisdomme ]
softdepend: [ PlaceholderAPI, Vault ]
